version: '3.4'

services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: db_GerenciadorHospitalar
    ports:
      - "3308:3306"
    expose:
      - "3306"
    networks:
      - arj-network

  arj-sping-boot:
    image: ygoraraujorb/gerenciador-hospitalar
    restart: always
    build: ./Back-end
    working_dir: /Back-end
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/db_GerenciadorHospitalar?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSl=false
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    command: mvn spring-boot:run
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - arj-network

networks:
  arj-network:
    driver: bridge
